### ISSUE TITLE
Setup Initial Master Server Django App

### ISSUE THREAD

**Issue by DragonmasterJ** [brata-hsdc/brata#90]
Need to setup the initial django application for the master server conversion.

**Comment by jawaad-ahmad** [comment]
I think this one is continued by brata-hsdc/brata.masterserver#4.

**Comment by ellerychan** [comment]
I say close this one as redundant and not attached to the relevant repo.

**Comment by jawaad-ahmad** [comment]
For now, I'm fine with closing some of these issues directly since we're still refining our process and cleaning up from the migration. Eventually it would be good to have a process in-place that we follow to get PTRs moving through the various states, especially so we don't close an issue too early before it's gotten tested.

**Comment by ellerychan** [comment]
Created **Define low-overhead issue management process** #91 for you.
This issue will be handled in brata-hsdc/brata.masterserver#11.

**Comment by DragonmasterJ** [comment]
I figured we'd have the link in the closed redundant issues in the description so we wouldn't have to dig in the comments. 

This has me wondering - as the assignee, Ellery can you change the description, or is that limited to the issue creator? 

Also, I don't know if it was from our Google Code tags or a GitHub default, but for completeness I figure we can add the duplicate tag to all these issues as well.

**Comment by ellerychan** [comment]
If by "description" you mean the title, it appears that I can edit the title of this Issue.

If we put the reference to the other issue in the title, will it get hyperlinked?

**Comment by DragonmasterJ** [comment]
I was thinking the 'issue text' itself, which I think is known as the 'description' in GitHub at least when creating the issue. It may just be treated as comment when the issue is actually published. In the case it's treated as a comment, then I assume the creator will just have to edit top comment for those kinds of changes. 

I'm not sure if the hashtag works in the title. But I think it works better to be in the top comment. I think tracking issues would get cumbersome with those kinds of links in the title.
